### ISSUE TITLE
Make plugin available using package control

### ISSUE THREAD

**Issue by mriehl** [markbirbeck/sublime-text-irc#16]
Hi,

Do you have any plans on making sublime-text-irc available through [package control](http://wbond.net/sublime_packages/package_control)?
The plugin works really well for me, and I'd like to persist it in my "plugin list" so that it is automatically installed on each of my machines. That only works with package control compatible plugins, though...

If not - what's blocking you?

Regards,
max

**Comment by markbirbeck** [comment]
Thanks Max. Will definitely do this.

**Comment by markbirbeck** [comment]
For reference, here are the instructions on how to do this:

http://wbond.net/sublime_packages/package_control/package_developers

**Comment by markbirbeck** [comment]
Forgot to close this. Implemented here:

https://github.com/wbond/package_control_channel/pull/1911
