### ISSUE TITLE
"Find In Files" Doesn't Work with IRC Active

### ISSUE THREAD

**Issue by AnUnpronounceableName** [markbirbeck/sublime-text-irc#17]
When I'm in a room, my favorite find command (Find in Files, ctrl+shift+3) doesn't seem to work.

**Comment by markbirbeck** [comment]
I just tried the equivalent Mac command -- `[SHIFT]+[CMD]+F` -- and that correctly brings up _Find in Files_.

Is `[SHIFT]+[CTRL]+3` the Windows version? Or have you mapped it?

The only key I map in the code is `[ENTER]` so I'm a bit surprised at this.

**Comment by AnUnpronounceableName** [comment]
Hmm, something else must have been going on. Appears to entirely be a coincidence, and restarting Sublime (twice) fixed whatever else was causing the issue.
